dist/logger/objects/WELLog__c.object
<CustomObject>
    <label>WELLog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/logger/objects/WELLog__c/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

retrieveUnpackaged/objects/WELLogSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Logging_Level_API__c</fullName>
        <description>Define the logging level upper limit to be persisted into API.</description>
        <label>Logging Level API</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NONE</fullName>
                    <default>true</default>
                    <label>NONE</label>
                </value>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>WARN</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>DEBUG</fullName>
                </value>
                <value>
                    <fullName>FINE</fullName>
                </value>
                <value>
                    <fullName>FINER</fullName>
                </value>
                <value>
                    <fullName>FINEST</fullName>
                </value>
                <value>
                    <fullName>FINE,</fullName>
                    <isActive>false</isActive>
                    <label>FINE,</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Logging_Level_Database__c</fullName>
        <description>Define the logging level upper limit to be persisted into database.</description>
        <label>Logging Level Database</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NONE</fullName>
                    <default>true</default>
                    <label>NONE</label>
                </value>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>WARN</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>DEBUG</fullName>
                </value>
                <value>
                    <fullName>FINE</fullName>
                </value>
                <value>
                    <fullName>FINER</fullName>
                </value>
                <value>
                    <fullName>FINEST</fullName>
                </value>
                <value>
                    <fullName>FINE,</fullName>
                    <isActive>false</isActive>
                    <label>FINE,</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Logging_Level_Debug__c</fullName>
        <description>Define the logging level upper limit to be persisted into Salesforce Debug Log.</description>
        <label>Logging Level Debug</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NONE</fullName>
                    <default>true</default>
                    <label>NONE</label>
                </value>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>WARN</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>DEBUG</fullName>
                </value>
                <value>
                    <fullName>FINE</fullName>
                </value>
                <value>
                    <fullName>FINER</fullName>
                </value>
                <value>
                    <fullName>FINEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>WELLog Setting</label>
    <pluralLabel>WELLog Settings</pluralLabel>
</CustomObject>

src-force/sample/classes/WELSampleController.cls
public with sharing class WELSampleController {
    private static WELLogger.ILogger logger = WELLogger.get('sample:controller');

    public class Response {
        @AuraEnabled
        Object logs { get; set; }
    }

    @RemoteAction
    @AuraEnabled
    public static Response doSomeWork(String param1, Decimal param2) {
        logger.debug('[M:E] doSomeWork()'); // log for method enter
        logger.debug('[P:param1]', param1); // log for parameter
        logger.debug('[P:param2]', param2); // log for parameter

        Response res = new Response();
        try {
            logger.debug(LoggingLevel.INFO, 'doing lots of uninteresting work');
            logger.debug(LoggingLevel.WARN, 'doing some work');
            logger.debug(LoggingLevel.INFO, 'doing lots of uninteresting work');
            logger.debug(LoggingLevel.WARN, 'doing some work');
            logger.debug('a list of objects', [
                SELECT
                    MasterLabel,
                    Enabled__c,
                    Logging_Level_Database__c,
                    Logging_Level_Debug__c,
                    Logging_Level_API__c
                FROM WELLogSetting__mdt
            ]);
            invokeNullReferenceException();
        } catch (DmlException ex) {
            logger.get('ex').debug(LoggingLevel.ERROR, ex); // use ex as modifier
        } catch(Exception ex) {
            logger.get('ex').debug(LoggingLevel.ERROR, ex); // use ex as modifier
        } finally {
            WELLogger.save();          // output to database
            res.logs = WELLogger.logs; // output to browser
        }

        logger.debug('[M:X] doSomeWork()'); // log for method exit
        return res;
    }

    static void invokeNullReferenceException() {
        String s;
        s.toLowerCase();
    }

    static void invokeDMLException() {
        WELLog__c log = new WELLog__c(
            Namespace__c =
                'aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee' +
                'aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee' +
                'aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee' +
                'aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee' +
                'aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee' +
                '123456'
        );
        insert log;
    }
}